-- Create Entity Schemas table
CREATE TABLE IF NOT EXISTS entity_schemas (
    id UUID PRIMARY KEY,
    tenant_id VARCHAR(255) NOT NULL,
    entity_slug VARCHAR(255) NOT NULL,
    custom_fields JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(tenant_id, entity_slug)
);

-- Add custom_fields JSONB column to all primary tables
ALTER TABLE abc_analysis ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_abc_analysis_custom_fields ON abc_analysis USING GIN (custom_fields);
ALTER TABLE analytics_kpis ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_analytics_kpis_custom_fields ON analytics_kpis USING GIN (custom_fields);
ALTER TABLE analytics_machine_utilization ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_analytics_machine_utilization_custom_fields ON analytics_machine_utilization USING GIN (custom_fields);
ALTER TABLE analytics_revenue ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_analytics_revenue_custom_fields ON analytics_revenue USING GIN (custom_fields);
ALTER TABLE analytics_vendor_defects ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_analytics_vendor_defects_custom_fields ON analytics_vendor_defects USING GIN (custom_fields);
ALTER TABLE appearance_approval_reports ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_appearance_approval_reports_custom_fields ON appearance_approval_reports USING GIN (custom_fields);
ALTER TABLE apqp_gate_reviews ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_apqp_gate_reviews_custom_fields ON apqp_gate_reviews USING GIN (custom_fields);
ALTER TABLE apqp_milestones ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_apqp_milestones_custom_fields ON apqp_milestones USING GIN (custom_fields);
ALTER TABLE apqp_project_timelines ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_apqp_project_timelines_custom_fields ON apqp_project_timelines USING GIN (custom_fields);
ALTER TABLE audit_infractions ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_audit_infractions_custom_fields ON audit_infractions USING GIN (custom_fields);
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_audit_logs_custom_fields ON audit_logs USING GIN (custom_fields);
ALTER TABLE audit_logs_y2025 ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_audit_logs_y2025_custom_fields ON audit_logs_y2025 USING GIN (custom_fields);
ALTER TABLE audit_logs_y2026 ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_audit_logs_y2026_custom_fields ON audit_logs_y2026 USING GIN (custom_fields);
ALTER TABLE audit_logs_y2027 ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_audit_logs_y2027_custom_fields ON audit_logs_y2027 USING GIN (custom_fields);
ALTER TABLE auth_attendance ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_auth_attendance_custom_fields ON auth_attendance USING GIN (custom_fields);
ALTER TABLE calibration_matrices ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_calibration_matrices_custom_fields ON calibration_matrices USING GIN (custom_fields);
ALTER TABLE capability_reports ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_capability_reports_custom_fields ON capability_reports USING GIN (custom_fields);
ALTER TABLE change_impact_analyses ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_change_impact_analyses_custom_fields ON change_impact_analyses USING GIN (custom_fields);
ALTER TABLE change_notices ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_change_notices_custom_fields ON change_notices USING GIN (custom_fields);
ALTER TABLE change_requests ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_change_requests_custom_fields ON change_requests USING GIN (custom_fields);
ALTER TABLE chart_of_accounts ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_chart_of_accounts_custom_fields ON chart_of_accounts USING GIN (custom_fields);
ALTER TABLE companies ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_companies_custom_fields ON companies USING GIN (custom_fields);
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_contacts_custom_fields ON contacts USING GIN (custom_fields);
ALTER TABLE control_plans ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_control_plans_custom_fields ON control_plans USING GIN (custom_fields);
ALTER TABLE copq_logs ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_copq_logs_custom_fields ON copq_logs USING GIN (custom_fields);
ALTER TABLE cost_calculations ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_cost_calculations_custom_fields ON cost_calculations USING GIN (custom_fields);
ALTER TABLE customer_complaints ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_customer_complaints_custom_fields ON customer_complaints USING GIN (custom_fields);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_customers_custom_fields ON customers USING GIN (custom_fields);
ALTER TABLE cycle_counts ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_cycle_counts_custom_fields ON cycle_counts USING GIN (custom_fields);
ALTER TABLE departments ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_departments_custom_fields ON departments USING GIN (custom_fields);
ALTER TABLE dimensional_reports ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_dimensional_reports_custom_fields ON dimensional_reports USING GIN (custom_fields);
ALTER TABLE downtime_logs ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_downtime_logs_custom_fields ON downtime_logs USING GIN (custom_fields);
ALTER TABLE drawing_vault_documents ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_drawing_vault_documents_custom_fields ON drawing_vault_documents USING GIN (custom_fields);
ALTER TABLE drawings ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_drawings_custom_fields ON drawings USING GIN (custom_fields);
ALTER TABLE ecns ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_ecns_custom_fields ON ecns USING GIN (custom_fields);
ALTER TABLE eight_d_reports ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_eight_d_reports_custom_fields ON eight_d_reports USING GIN (custom_fields);
ALTER TABLE engineering_tool_assets ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_engineering_tool_assets_custom_fields ON engineering_tool_assets USING GIN (custom_fields);
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_expenses_custom_fields ON expenses USING GIN (custom_fields);
ALTER TABLE fais ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_fais_custom_fields ON fais USING GIN (custom_fields);
ALTER TABLE finance_accounts ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_finance_accounts_custom_fields ON finance_accounts USING GIN (custom_fields);
ALTER TABLE finance_copq_logs ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_finance_copq_logs_custom_fields ON finance_copq_logs USING GIN (custom_fields);
ALTER TABLE finance_expenses ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_finance_expenses_custom_fields ON finance_expenses USING GIN (custom_fields);
ALTER TABLE finance_invoices ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_finance_invoices_custom_fields ON finance_invoices USING GIN (custom_fields);
ALTER TABLE finance_journal_entries ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_finance_journal_entries_custom_fields ON finance_journal_entries USING GIN (custom_fields);
ALTER TABLE finance_journal_lines ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_finance_journal_lines_custom_fields ON finance_journal_lines USING GIN (custom_fields);
ALTER TABLE finance_projects ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_finance_projects_custom_fields ON finance_projects USING GIN (custom_fields);
ALTER TABLE finance_purchase_orders ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_finance_purchase_orders_custom_fields ON finance_purchase_orders USING GIN (custom_fields);
ALTER TABLE gauge_rnr_studies ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_gauge_rnr_studies_custom_fields ON gauge_rnr_studies USING GIN (custom_fields);
ALTER TABLE gauge_rnrs ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_gauge_rnrs_custom_fields ON gauge_rnrs USING GIN (custom_fields);
ALTER TABLE hrms_attendance ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_hrms_attendance_custom_fields ON hrms_attendance USING GIN (custom_fields);
ALTER TABLE hrms_employees ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_hrms_employees_custom_fields ON hrms_employees USING GIN (custom_fields);
ALTER TABLE hrms_leaves ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_hrms_leaves_custom_fields ON hrms_leaves USING GIN (custom_fields);
ALTER TABLE hrms_tasks ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_hrms_tasks_custom_fields ON hrms_tasks USING GIN (custom_fields);
ALTER TABLE inventory_delivery_challans ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_inventory_delivery_challans_custom_fields ON inventory_delivery_challans USING GIN (custom_fields);
ALTER TABLE inventory_items ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_inventory_items_custom_fields ON inventory_items USING GIN (custom_fields);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_invoices_custom_fields ON invoices USING GIN (custom_fields);
ALTER TABLE job_work_challans ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_job_work_challans_custom_fields ON job_work_challans USING GIN (custom_fields);
ALTER TABLE journal_entries ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_journal_entries_custom_fields ON journal_entries USING GIN (custom_fields);
ALTER TABLE journal_lines ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_journal_lines_custom_fields ON journal_lines USING GIN (custom_fields);
ALTER TABLE machine_capacities ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_machine_capacities_custom_fields ON machine_capacities USING GIN (custom_fields);
ALTER TABLE machine_telemetry_logs ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_machine_telemetry_logs_custom_fields ON machine_telemetry_logs USING GIN (custom_fields);
ALTER TABLE machine_telemetry_logs_y2025 ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_machine_telemetry_logs_y2025_custom_fields ON machine_telemetry_logs_y2025 USING GIN (custom_fields);
ALTER TABLE machine_telemetry_logs_y2026 ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_machine_telemetry_logs_y2026_custom_fields ON machine_telemetry_logs_y2026 USING GIN (custom_fields);
ALTER TABLE machine_telemetry_logs_y2027 ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_machine_telemetry_logs_y2027_custom_fields ON machine_telemetry_logs_y2027 USING GIN (custom_fields);
ALTER TABLE machines ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_machines_custom_fields ON machines USING GIN (custom_fields);
ALTER TABLE maintenance_logs ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_maintenance_logs_custom_fields ON maintenance_logs USING GIN (custom_fields);
ALTER TABLE material_certificates ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_material_certificates_custom_fields ON material_certificates USING GIN (custom_fields);
ALTER TABLE material_certifications ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_material_certifications_custom_fields ON material_certifications USING GIN (custom_fields);
ALTER TABLE material_heat_numbers ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_material_heat_numbers_custom_fields ON material_heat_numbers USING GIN (custom_fields);
ALTER TABLE modules ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_modules_custom_fields ON modules USING GIN (custom_fields);
ALTER TABLE mold_projects ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_mold_projects_custom_fields ON mold_projects USING GIN (custom_fields);
ALTER TABLE oee_daily_metrics ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_oee_daily_metrics_custom_fields ON oee_daily_metrics USING GIN (custom_fields);
ALTER TABLE open_risk_trackers ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_open_risk_trackers_custom_fields ON open_risk_trackers USING GIN (custom_fields);
ALTER TABLE payment_receipts ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_payment_receipts_custom_fields ON payment_receipts USING GIN (custom_fields);
ALTER TABLE permissions ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_permissions_custom_fields ON permissions USING GIN (custom_fields);
ALTER TABLE pfmeas ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_pfmeas_custom_fields ON pfmeas USING GIN (custom_fields);
ALTER TABLE plants ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_plants_custom_fields ON plants USING GIN (custom_fields);
ALTER TABLE ppap_submissions ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_ppap_submissions_custom_fields ON ppap_submissions USING GIN (custom_fields);
ALTER TABLE preventive_maintenance_schedules ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_preventive_maintenance_schedules_custom_fields ON preventive_maintenance_schedules USING GIN (custom_fields);
ALTER TABLE process_flow_diagrams ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_process_flow_diagrams_custom_fields ON process_flow_diagrams USING GIN (custom_fields);
ALTER TABLE procurement_purchase_orders ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_procurement_purchase_orders_custom_fields ON procurement_purchase_orders USING GIN (custom_fields);
ALTER TABLE production_jobs ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_production_jobs_custom_fields ON production_jobs USING GIN (custom_fields);
ALTER TABLE production_schedules ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_production_schedules_custom_fields ON production_schedules USING GIN (custom_fields);
ALTER TABLE project_cost_analysis ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_project_cost_analysis_custom_fields ON project_cost_analysis USING GIN (custom_fields);
ALTER TABLE project_tasks ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_project_tasks_custom_fields ON project_tasks USING GIN (custom_fields);
ALTER TABLE psws ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_psws_custom_fields ON psws USING GIN (custom_fields);
ALTER TABLE quality_control_plans ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_quality_control_plans_custom_fields ON quality_control_plans USING GIN (custom_fields);
ALTER TABLE quality_pfmeas ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_quality_pfmeas_custom_fields ON quality_pfmeas USING GIN (custom_fields);
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_quotations_custom_fields ON quotations USING GIN (custom_fields);
ALTER TABLE refurbishment_tickets ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_refurbishment_tickets_custom_fields ON refurbishment_tickets USING GIN (custom_fields);
ALTER TABLE rfqs ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_rfqs_custom_fields ON rfqs USING GIN (custom_fields);
ALTER TABLE role_permissions ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_role_permissions_custom_fields ON role_permissions USING GIN (custom_fields);
ALTER TABLE roles ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_roles_custom_fields ON roles USING GIN (custom_fields);
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_sessions_custom_fields ON sessions USING GIN (custom_fields);
ALTER TABLE shifts ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_shifts_custom_fields ON shifts USING GIN (custom_fields);
ALTER TABLE spc_studies ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_spc_studies_custom_fields ON spc_studies USING GIN (custom_fields);
ALTER TABLE stock_transactions ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_stock_transactions_custom_fields ON stock_transactions USING GIN (custom_fields);
ALTER TABLE supplier_audits ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_supplier_audits_custom_fields ON supplier_audits USING GIN (custom_fields);
ALTER TABLE supplier_ncrs ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_supplier_ncrs_custom_fields ON supplier_ncrs USING GIN (custom_fields);
ALTER TABLE supplier_scorecards ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_supplier_scorecards_custom_fields ON supplier_scorecards USING GIN (custom_fields);
ALTER TABLE tool_assets ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_tool_assets_custom_fields ON tool_assets USING GIN (custom_fields);
ALTER TABLE tooling_life_logs ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_tooling_life_logs_custom_fields ON tooling_life_logs USING GIN (custom_fields);
ALTER TABLE tooling_projects ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_tooling_projects_custom_fields ON tooling_projects USING GIN (custom_fields);
ALTER TABLE traveler_stages ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_traveler_stages_custom_fields ON traveler_stages USING GIN (custom_fields);
ALTER TABLE travelers ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_travelers_custom_fields ON travelers USING GIN (custom_fields);
ALTER TABLE user_roles ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_user_roles_custom_fields ON user_roles USING GIN (custom_fields);
ALTER TABLE users ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_users_custom_fields ON users USING GIN (custom_fields);
ALTER TABLE vendor_quality_scores ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_vendor_quality_scores_custom_fields ON vendor_quality_scores USING GIN (custom_fields);
ALTER TABLE warehouses ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_warehouses_custom_fields ON warehouses USING GIN (custom_fields);
ALTER TABLE workflow_definitions ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_workflow_definitions_custom_fields ON workflow_definitions USING GIN (custom_fields);
ALTER TABLE workflow_history ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_workflow_history_custom_fields ON workflow_history USING GIN (custom_fields);
ALTER TABLE workflow_instances ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_workflow_instances_custom_fields ON workflow_instances USING GIN (custom_fields);
ALTER TABLE workflow_steps ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_workflow_steps_custom_fields ON workflow_steps USING GIN (custom_fields);
