"use client";

import React from "react";
import { useParams, useRouter } from "next/navigation";
import { useProject } from "@/hooks/useProjects";
import { useMasterData } from "@/hooks/useMasterData";
import { BomConverter } from "@/components/engineering/BomConverter";
import { SkeletonBox } from "@/components/ui/SkeletonLoader";
import { useUpdateBOM } from "@/hooks/useEngineering";
import { useToast } from "@/components/ui/Toast";
import { ProcurementService } from "@/services/procurement.service";
import { Cpu } from "lucide-react";

export default function ProjectEngineeringPage() {
  const params = useParams();
  const router = useRouter();
  const id = params?.id as string;
  const { data: project, isLoading } = useProject(id);
  const { data: rawMaterials = [] } = useMasterData('raw-materials');
  const updateBOMMutation = useUpdateBOM(id);
  const { success, error } = useToast();

  const handleSaveBOM = async (rows: any[]) => {
    try {
      const stdMatId = rawMaterials.find((m: any) => m.materialCode === 'STD')?.id;
      const items = rows.map(r => ({
        materialId: r.matchedMaterialId || (r.isBoughtOut ? stdMatId : r.materialId),
        requiredQty: Number(r.quantity) || 1,
        estimatedCost: Number(r.basicCost) || 0,
        rawSize: r.rawMaterialSize || r.rawSize || '',
        calculatedWeight: Number(r.totalWeight) || 0,
        dimensions: r.length && r.width && r.height ? `${r.length}x${r.width}x${r.height}` : undefined,
        hsnCode: r.hsnCode || undefined,
        gstPercent: r.gstPercent || undefined,
        customFields: {
          srNo: r.srNo,
          partName: r.partName || project?.partName || project?.name || '',
          finishSize: r.finishSize,
          rawMaterialSize: r.rawMaterialSize,
          length: r.length,
          width: r.width,
          height: r.height,
          apWeight: r.apWeight,
          totalWeight: r.totalWeight,
          basicCost: r.basicCost,
          isBoughtOut: r.isBoughtOut || false,
          unitCost: r.unitCost || 0,
          materialInput: r.materialInput || (r.isBoughtOut ? 'STD' : ''),
          rate: r.rate
        }
      }));
      await updateBOMMutation.mutateAsync({ items });
      success("BOM Saved", "Bill of Materials saved successfully.");
    } catch (err: any) {
      error("Error", err.message || "Failed to save BOM");
      throw err;
    }
  };

  const handleProceedToPO = async (rows: any[]) => {
    try {
      // 1. First save BOM items to database
      await handleSaveBOM(rows);

      // 2. Automatically generate Purchase Order in database
      const poItems = rows.map((r, idx) => ({
        materialId: r.matchedMaterialId || undefined,
        orderedQty: Number(r.quantity) || 1,
        agreedRate: Number(r.rate) || 0,
        basicValue: Number(r.basicCost) || 0,
        dimensions: r.rawMaterialSize || (r.length && r.width && r.height ? `${r.length} x ${r.width} x ${r.height}` : ''),
        hsnCode: r.hsnCode || '',
        gstPercent: Number(r.gstPercent) || 18,
        remarks: r.partName || r.description || `BOM Item #${r.srNo || idx + 1}`,
        customFields: {
          toolNo: r.toolNo || project?.projectNumber || 'PRJ-TOOL',
          detNo: String(r.srNo || idx + 1),
          length: String(r.length || ''),
          width: String(r.width || ''),
          height: String(r.height || ''),
          materialGrade: r.materialInput || 'MS',
          apWt: Number(r.apWeight) || 0,
          totalWt: Number(r.totalWeight) || 0,
          gstAmount: Number(r.basicCost ? r.basicCost * 0.18 : 0),
          lineTotal: Number(r.basicCost ? r.basicCost * 1.18 : 0)
        }
      }));

      const generatedPoNum = `PO/${project?.projectNumber || 'TOOL'}/${Date.now().toString().slice(-4)}`;

      const poPayload = {
        projectId: id,
        poNumber: generatedPoNum,
        expectedDeliveryDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
        remarks: `Auto-generated PO from BOM (${rows.length} Items)`,
        customFields: {
          rmSlipNo: `RM-${project?.projectNumber || 'SLIP'}-${Date.now().toString().slice(-4)}`,
          vendorName: 'Primary Raw Material Supplier',
          isAutoGeneratedFromBOM: true,
        },
        items: poItems,
      };

      let poCreated = false;
      try {
        await ProcurementService.createPurchaseOrder(id, poPayload);
        poCreated = true;
      } catch (e1) {
        try {
          await ProcurementService.createMultiProjectPo(poPayload);
          poCreated = true;
        } catch (e2: any) {
          console.error("Auto PO generation error:", e2);
          error("PO Generation Failed", e2?.response?.data?.message || e2?.message || "Failed to create PO");
        }
      }

      if (poCreated) {
        success("Purchase Order Created Automatically!", `Generated PO ${generatedPoNum} for ${poItems.length} BOM items.`);
      }

      // 3. Navigate directly to project purchase page
      router.push(`/projects/${id}/purchase`);

    } catch (e) {
      // Handled in handleSaveBOM
    }
  };

  if (isLoading) {
    return <SkeletonBox className="h-96 w-full" />;
  }

  return (
    <div className="space-y-6">
      {/* Standard Module Header Card */}
      <div className="bg-white border border-border-gray rounded-[12px] p-5 shadow-subtle flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2.5 mb-1">
            <div className="h-8 w-8 rounded-[12px] bg-primary flex items-center justify-center shadow-sm shrink-0">
              <Cpu className="h-4 w-4 text-white" />
            </div>
            <h1 className="text-xl font-semibold text-ink tracking-tight">
              Engineering BOM & Procurement Converter
            </h1>
          </div>
          <p className="text-xs text-mute ml-[42px]">
            Upload, convert, validate and sign off project Bill of Materials (BOM) to generate purchase requisitions.
          </p>
        </div>
      </div>

      <BomConverter
        projectId={id}
        project={project}
        materials={rawMaterials}
        onSaveBOM={handleSaveBOM}
        onProceedToPO={handleProceedToPO}
      />
    </div>
  );
}


