"use client";

import React from "react";
import { useParams, useRouter } from "next/navigation";
import { useProject } from "@/hooks/useProjects";
import { useMasterData } from "@/hooks/useMasterData";
import { BomConverter } from "@/components/engineering/BomConverter";
import { SkeletonBox } from "@/components/ui/SkeletonLoader";
import { useUpdateBOM } from "@/hooks/useEngineering";
import { useToast } from "@/components/ui/Toast";
import { ProcurementService } from "@/services/procurement.service";

export default function ProjectEngineeringPage() {
  const params = useParams();
  const router = useRouter();
  const id = params?.id as string;
  const { data: project, isLoading } = useProject(id);
  const { data: rawMaterials = [] } = useMasterData('raw-materials');
  const updateBOMMutation = useUpdateBOM(id);
  const { success, error } = useToast();

  const handleSaveBOM = async (rows: any[]) => {
    try {
      const items = rows.map(r => ({
        materialId: r.matchedMaterialId || r.materialId,
        requiredQty: r.quantity || r.requiredQty,
        estimatedCost: r.basicCost || r.estimatedCost || 0,
        rawSize: r.rawMaterialSize || r.rawSize || '',
        calculatedWeight: r.totalWeight || r.calculatedWeight || 0,
        dimensions: r.length && r.width && r.height ? `${r.length}x${r.width}x${r.height}` : undefined,
        hsnCode: r.hsnCode || undefined,
        gstPercent: r.gstPercent || undefined,
        customFields: {
          srNo: r.srNo,
          partName: r.partName || project?.partName || project?.name || '',
          finishSize: r.finishSize,
          rawMaterialSize: r.rawMaterialSize,
          length: r.length,
          width: r.width,
          height: r.height,
          apWeight: r.apWeight,
          totalWeight: r.totalWeight,
          basicCost: r.basicCost
        }
      }));
      await updateBOMMutation.mutateAsync({ items });
      success("BOM Saved", "Bill of Materials saved successfully.");
    } catch (err: any) {
      error("Error", err.message || "Failed to save BOM");
      throw err;
    }
  };

  const handleProceedToPO = async (rows: any[]) => {
    try {
      // 1. First save BOM items to database
      await handleSaveBOM(rows);

      // 2. Automatically generate Purchase Order in database
      const poItems = rows.map((r, idx) => ({
        materialId: r.matchedMaterialId || undefined,
        orderedQty: Number(r.quantity) || 1,
        agreedRate: Number(r.rate) || 0,
        basicValue: Number(r.basicCost) || 0,
        dimensions: r.rawMaterialSize || (r.length && r.width && r.height ? `${r.length} x ${r.width} x ${r.height}` : ''),
        hsnCode: r.hsnCode || '',
        gstPercent: Number(r.gstPercent) || 18,
        remarks: r.partName || r.description || `BOM Item #${r.srNo || idx + 1}`,
        customFields: {
          toolNo: r.toolNo || project?.projectNumber || 'PRJ-TOOL',
          detNo: String(r.srNo || idx + 1),
          length: String(r.length || ''),
          width: String(r.width || ''),
          height: String(r.height || ''),
          materialGrade: r.materialInput || 'MS',
          apWt: Number(r.apWeight) || 0,
          totalWt: Number(r.totalWeight) || 0,
          gstAmount: Number(r.basicCost ? r.basicCost * 0.18 : 0),
          lineTotal: Number(r.basicCost ? r.basicCost * 1.18 : 0)
        }
      }));

      const generatedPoNum = `PO/${project?.projectNumber || 'TOOL'}/${Date.now().toString().slice(-4)}`;

      const poPayload = {
        projectId: id,
        poNumber: generatedPoNum,
        expectedDeliveryDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
        remarks: `Auto-generated PO from BOM (${rows.length} Items)`,
        customFields: {
          rmSlipNo: `RM-${project?.projectNumber || 'SLIP'}-${Date.now().toString().slice(-4)}`,
          vendorName: 'Primary Raw Material Supplier',
          isAutoGeneratedFromBOM: true,
        },
        items: poItems,
      };

      let poCreated = false;
      try {
        await ProcurementService.createPurchaseOrder(id, poPayload);
        poCreated = true;
      } catch (e1) {
        try {
          await ProcurementService.createMultiProjectPo(poPayload);
          poCreated = true;
        } catch (e2: any) {
          console.error("Auto PO generation error:", e2);
          error("PO Generation Failed", e2?.response?.data?.message || e2?.message || "Failed to create PO");
        }
      }

      if (poCreated) {
        success("Purchase Order Created Automatically!", `Generated PO ${generatedPoNum} for ${poItems.length} BOM items.`);
      }

      // 3. Navigate directly to project purchase page
      router.push(`/projects/${id}/purchase`);

    } catch (e) {
      // Handled in handleSaveBOM
    }
  };

  if (isLoading) {
    return <SkeletonBox className="h-96 w-full" />;
  }

  return (
    <div className="space-y-6">
      <BomConverter
        projectId={id}
        project={project}
        materials={rawMaterials}
        onSaveBOM={handleSaveBOM}
        onProceedToPO={handleProceedToPO}
      />
    </div>
  );
}


