export class BomSummaryProjection {
  id: string;
  projectId: string;
  projectNumber?: string;
  bomNumber: string | null;
  documentNumber: string | null;
  revision: number;
  revisionDate: Date | null;
  status: string;
  approvalStatus: string;
  totalEstimatedCost: number;
  updatedAt: Date;
}

export class BomItemProjection {
  id: string;
  materialId: string;
  partNo: string | null;
  partName: string | null;
  finishSize: string | null;
  rawSize: string | null;
  requiredQty: number;
  unitCost: number;
  estimatedCost: number;
  remarks: string | null;
}

export class BomDetailsProjection extends BomSummaryProjection {
  items: BomItemProjection[];
}

export class BomTreeProjection extends BomSummaryProjection {
  tree: any; // Complex nested structure generated by BomTreeService
}
